### ISSUE TITLE
How to import jsonPrototype?

### ISSUE THREAD

**Issue by dinkom** [peter-ahr/jsonPrototypeJS#1]
Hi, I'm trying to use this library inside my React/ES6 project (I initially stumbled upon RessurectJS, but it didn't do the trick for my use case), but I cannot find how to import it in the docs. I've installed it through yarn and tried:

```
import jsonPrototype from 'json_prototype';
```
and
```
import jsonPrototype from 'jsonPrototype';
```

I can see the library inside my `node_modules` and it's listed as a dependency inside `package.json` so there's no doubt whether it's really here.

Am I importing it wrong?

**Comment by ayazzali** [comment]
me too. my logs:
C:\Users\Ayaz\source\repos\newreactnative\BugsByKey>node C:\Users\Ayaz\source\repos\newreactnative\BugsByKey\t.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'json_prototype'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Ayaz\source\repos\newreactnative\BugsByKey\t.js:6:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by ayazzali** [comment]
i added 
"main": "jsonprototype.js",
to project.json
and it worked!
